import { cdnBase } from '../config/index';
const imgPrefix = cdnBase;

const defaultDesc = [`${imgPrefix}/goods/details-1.png`];

const allGoods = [
  {
    saasId: '88888888',
    storeId: '1000',
    spuId: '0',
    title: '连衣裙',
    resume: '白色短袖连衣裙荷叶边裙摆宽松韩版休闲纯白清爽优雅连衣裙',
    primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
    images: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09b.png',
    ],
    available: 1,
    minSalePrice: 29800,
    minLinePrice: 29800,
    maxSalePrice: 29800,
    maxLinePrice: 40000,
    spuStockQuantity: 510,
    soldNum: 1020,
    isPutOnSale: 1,
    desc: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09c.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09d.png',
    ],
    etitle: '',
  },
  {
    saasId: '88888888',
    storeId: '1000',
    spuId: '135686633',
    title: 'T恤',
    resume: '纯色纯棉休闲圆领短袖T恤纯白亲肤厚柔软细腻面料纯白短袖套头T恤',
    primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08b.png',
    minSalePrice: '25900',
    minLinePrice: '31900',
    maxSalePrice: '26900',
    maxLinePrice: '31900',
    isSoldOut: false,
    images: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08a.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08a1.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08b.png',
    ],
    groupIdList: ['15029', '14023'],
    isAvailable: 1,
    spuStockQuantity: 371,
    soldNum: 1032,
    isPutOnSale: 1,
    promotionList: null,
    minProfitPrice: null,
    etitle: '',
    desc: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08c.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08d.png',
    ],
  },
  {
    saasId: '88888888',
    storeId: '1000',
    spuId: '135691628',
    title: '运动上衣',
    resume: '运动连帽拉链卫衣休闲开衫长袖多色运动细绒面料运动上衣',
    images: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-17a.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-17a1.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-17b.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-17b1.png',
    ],
    primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-17a.png',
    minSalePrice: '25900',
    minLinePrice: '39900',
    maxSalePrice: '25900',
    maxLinePrice: '39900',
    isSoldOut: true,
    groupIdList: ['15029', '14023'],
    isAvailable: 1,
    spuStockQuantity: 0,
    soldNum: 1022,
    isPutOnSale: 1,
    promotionList: null,
    minProfitPrice: null,
    etitle: '',
    desc: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-17c.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-17d.png',
    ],
  },
  {
    saasId: '88888888',
    storeId: '1000',
    spuId: '135686623',
    title: '机顶盒',
    resume: '腾讯极光盒子4智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率',
    primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-3a.png',
    images: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-3a.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-3b.png',
    ],
    minSalePrice: '9900',
    minLinePrice: '16900',
    maxSalePrice: '10900',
    maxLinePrice: '16900',
    isSoldOut: false,
    isAvailable: 1,
    spuStockQuantity: 598,
    soldNum: 102,
    isPutOnSale: 1,
    desc: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-3c.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-3d.png',
    ],
    promotionList: null,
    minProfitPrice: null,
    etitle: '',
  },
  {
    saasId: '88888888',
    storeId: '1000',
    spuId: '135681628',
    title: '午休毯连帽披肩',
    resume: '带帽午休毯虎年款多功能加厚加大加绒简约多功能午休毯连帽披肩',
    primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/muy-3a.png',
    images: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/muy-3a.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/muy-3a1.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/muy-3b.png',
    ],
    minSalePrice: '29900',
    minLinePrice: '39900',
    maxSalePrice: '39900',
    maxLinePrice: '39900',
    isSoldOut: false,
    desc: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/muy-3c.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/muy-3d.png',
    ],
    isAvailable: 1,
    spuStockQuantity: 321,
    soldNum: 102,
    isPutOnSale: 1,
    promotionList: null,
    minProfitPrice: null,
    etitle: '',
  },
  {
    saasId: '88888888',
    storeId: '1000',
    spuId: '135681626',
    title: '耳机',
    resume: '迷你便携高颜值蓝牙无线耳机立体声只能触控式操作简约立体声耳机',
    primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-2a.png',
    images: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-2a.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-2a1.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-2b.png',
    ],
    minSalePrice: '29000',
    minLinePrice: '40000',
    maxSalePrice: '39000',
    maxLinePrice: '40000',
    isSoldOut: false,
    desc: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-2c.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-2d.png',
    ],
    isAvailable: 1,
    spuStockQuantity: 366,
    soldNum: 102,
    isPutOnSale: 1,
    promotionList: null,
    minProfitPrice: null,
    etitle: '',
  },
  {
    saasId: '88888888',
    storeId: '1000',
    spuId: '135681624',
    title: '不锈钢刀叉勺套装',
    resume: '不锈钢刀叉勺套装家用西餐餐具ins简约耐用不锈钢金色银色可选',
    primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/gh-2b.png',
    images: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/gh-2a.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/gh-2a1.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/gh-2b.png',
    ],
    video: null,
    available: 1,
    minSalePrice: '19900',
    minLinePrice: '19900',
    maxSalePrice: '29900',
    maxLinePrice: '29900',
    spuStockQuantity: 0,
    soldNum: 102,
    isPutOnSale: 1,
    desc: [
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/gh-2c.png',
      'https://cdn-we-retail.ym.tencent.com/tsr/goods/gh-2d.png',
    ],
    etitle: '',
  },
]

/**
 * @param {string} id
 * @param {number} [available] 库存, 默认1
 */
 export function genGood(id, available = 1) {
  const specID = ['135681624', '135681628'];
  if (specID.indexOf(id) > -1) {
    return allGoods.filter((good) => good.spuId === id)[0];
  }
  const item = allGoods[id % allGoods.length];
  return {
    ...item,
    spuId: `${id}`,
    available: available,
    desc: item?.desc || defaultDesc,
    images: item?.images || [item?.primaryImage],
  };
}